User/urls.py
from django.urls import path, include
from User import views

app_name = 'user'

urlpatterns = [
    path('login-oauth-page/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('register/', views.register_page, name='register_page'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from config.settings import MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Uzum/', include('shops.urls'), name='shops'),
    path('Customers/', include('customers.urls')),
    path('user/', include('User.urls'), name='users'),
    path('social-auth/', include('social_django.urls', namespace='social')),

] + static(MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from User.managers import UserManager

# Create your models here.

class User(AbstractUser):
    username = None
    email = models.EmailField('Email Address',
                          unique=True
                          )
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email

User/forms.py
from django import forms

from User.models import User


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("Email empty")

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("User does not exist")
        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("User does not exist")
        return password

    def clean(self):
        email = self.cleaned_data.get('email')


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=150,required=False)
    confirm_password = forms.CharField()

    class Meta:
        model = User
        fields = ['email', 'username', 'confirm_password', 'password']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email is None:
            raise forms.ValidationError("Email empty")

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f"User {email} already exists")
        return email


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

User/views.py
# import random
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from User.models import User
from config.settings import DEFAULT_FROM_EMAIL
from User.forms import LoginForm, RegisterForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from User.custom_token import account_activation_token
from django.core.mail import EmailMessage
from django.contrib import messages


# Create your views here.
# def generate_verification_code():
#     return str(random.randint(100000,999999))

def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                return redirect('shops:index')

            else:
                messages.add_message(request,messages.ERROR,'Invalid login')

    context = {
        'form': form,
    }

    return render(request, 'User/login.html', context=context)


def logout_page(request):
    logout(request)
    return redirect('shops:index')


def register_page(request):
    form = RegisterForm()
    if request.method ==     'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            email = form.cleaned_data['email']
            get_name_by_email = user.email.split('@')[0]
            user.set_password(user.password)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)

            subject = 'Verify your account'
            message = render_to_string('User/email-verification/verify_email_message.html',{
                'request': request,
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            email = EmailMessage(
                subject, message, to=[email]
            )
            email.content_subtype = 'html'
            email.send()
            data = 'You have been send email verification link ✉️'
            return HttpResponse(f'<h2>{data}</h2>')

            # user.set_password(form.cleaned_data['password'])
            # verification_code = generate_verification_code()
            # request.session['verification_code'] = verification_code

            # request.session['user_data'] = {
            #     'email': user.email,
            #     'password': form.cleaned_data['password'],
            #     'is_staff': user.is_staff,
            #     'is_superuser': user.is_superuser,
            # }
    context = {
            'form': form,
        }
    return render(request, 'User/register.html', context=context)


def verify_email_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        messages.success(request, 'Your email has been verified.')
        return redirect('user:verify-email-complete')

    else:
        messages.warning(request, 'The link is invalid.')
    return render(request, 'User/email-verification/verify_email_confirm.html')


def verify_email_complete(request):
    return render(request, 'User/email-verification/verify_email_complete.html')

# def verify_code(request):
#     if request.method == 'POST':
#         entered_code = request.POST.get('code')
#         stored_code = request.session.get('verification_code')
#         user_data = request.session.get('user_data')
#
#         if entered_code == stored_code:
#             del request.session['verification_code']
#             del request.session['user_data']
#             user = User.objects.create_user(
#                 email=user_data['email'],
#                 password=user_data['password'],
#                 is_staff=user_data['is_staff'],
#                 is_superuser=user_data['is_superuser']
#             )
#             login(request, user, backend='django.contrib.auth.backends.ModelBackend')
#             messages.add_message(request, messages.SUCCESS, 'Your Code has been verified')
#             return redirect('shops:index')
#         else:
#             messages.add_message(request, messages.ERROR, 'Invalid code')
#
#     return render(request, 'User/enter_number.html')

User/templates/User/email-verification/verify_email_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Check</title>
</head>
<body>
<div class="alert alert-success">
    You have successfully verified your e-mail
</div>
</body>
</html>

User/templates/User/email-verification/verify_email_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email</title>
</head>
<body>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>
</body>
</html>

User/templates/User/email-verification/verify_email_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Verification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            padding: 50px;
        }
        .container {
            background: #c2c2c2;
            padding: 15px;
            border-radius: 10px;
            max-width: 500px;
            margin: auto;
        }
        .header {
            margin: 0;
            padding: 10px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
            background-color: #5865F2;
            color: #ffffff;
            font-size: 20px;
            font-weight: bold;
        }
        .content {
            margin: 0;
            padding: 15px;
            background-color: #ffffff;
            border-bottom-left-radius: 10px;
            border-bottom-right-radius: 10px;
            text-align: left;
        }
        .button {
            display: inline-block;
            border: 0;
            color: #ffffff;
            background-color: #5865F2;
            padding: 15px;
            font-weight: bold;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 10px;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 14px;
        }
        .footer a {
            color: #5865F2;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="header">Verify Email</h2>
        <div class="content">
            <p>Hi {{ user.name }},</p>
            <p>You created an account on Delight.com, you need to verify your email. Please click on the button below to verify your email.</p>
            <a href="{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}" class="button">
                Verify Email
            </a>
            <p style="margin-top: 40px;">Or you can copy the link below to your browser</p>
            <p>{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}</p>
            <p>The Delight Team</p>
        </div>
        <div class="footer">
            <p>© {% now 'Y' %} <a href="https://delighto.medium.com">Blog</a></p>
            <p>Follow us on <a href="https://twitter.com/DelightGbolahan">Twitter</a></p>
        </div>
    </div>
</body>
</html>