User/urls.py
from django.urls import path, include
from User import views

app_name = 'user'

urlpatterns = [
    path('login-oauth-page/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('register/', views.register_page, name='register_page'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from config.settings import MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Uzum/', include('shops.urls'), name='shops'),
    path('Customers/', include('customers.urls')),
    path('user/', include('User.urls'), name='users'),
    path('social-auth/', include('social_django.urls', namespace='social')),

] + static(MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path, include
from customers import views

app_name = 'customers'

urlpatterns = [
    path('customer', views.customers, name='customer'),
    path('customers-detail/<int:pk>/', views.customer_details, name='customer_details'),
    path('edit-customer/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('create-customer/', views.create_customer, name='create_customer'),
    path('delete-customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('load-details/' , views.load_details, name='load_details'),
]

shops/urls.py
from django.urls import path
from shops import views
app_name = 'shops'

urlpatterns = [
    path('', views.index, name='index'),
    path('product-detail/<slug:slug>/', views.detail, name='detail'),
    path('category-choice/<slug:slug>/', views.index, name='category'),
    path('product-comment/<int:pk>/', views.comment, name='comment'),
    path('create-product/', views.CreateProduct.as_view(), name='create_product'),
    path('edit-product/<int:pk>/', views.EditProduct.as_view(), name='edit_product'),
    path('delete-product/<int:pk>/', views.delete_product, name='delete_product'),
    path('customer/<int:pk>/', views.app1_view, name='customer'),
    path('create-attrbute', views.CreateAttribute.as_view(), name='create_attribute'),
    path('create-attrbute-value', views.AttributeValeu.as_view(), name='create_attribute_value'),
    path('product-attribute/', views.CreateProductAttribute.as_view(), name='product-attribute'),
]

customers/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Customer(BaseModel):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    phone = PhoneNumberField(region='UZ', unique=True)
    address = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    VAT_number = models.CharField(max_length=100, unique=True,null=True,blank=True)
    password = models.CharField(max_length=100)


    def __str__(self):
        return f"{self.name} => {self.phone}"

    @property
    def image_url(self):
        return self.image.url

customers/forms.py
from django import forms

from customers.models import Customer


class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

shops/forms.py
from django import forms
from shops.models import Comment, Product, Attribute, AttributeValue, ProductAttribute


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','content']


class AttributeModelForm(forms.ModelForm):
    class Meta:
        model = Attribute
        fields = '__all__'

class AttributeValueModelForm(forms.ModelForm):
    class Meta:
        model = AttributeValue
        fields = '__all__'

class ProductAttributeForm(forms.ModelForm):
    class Meta:
        model = ProductAttribute
        fields = '__all__'

customers/views.py
import csv
import json
import pandas as pd
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from customers.forms import CustomerModelForm
from customers.models import Customer

# Create your views here.

def customers(request):
    search_query = request.GET.get('q', '')
    customers = Customer.objects.all()

    if search_query:
        customers = customers.filter(name__icontains=search_query)

    context = {
        'customers': customers
               }
    return render(request, 'customers/customer.html', context)

def customer_details(request,pk):
    customer = Customer.objects.get(pk=pk)

    context = {
        'customer': customer
    }

    return render(request,'customers/customer-details.html', context)


def create_customer(request):
    form =  CustomerModelForm()
    if request.method == 'POST':
        form = CustomerModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('customers:customer')
    else:
        form = CustomerModelForm()

    context = {
        'form': form
    }
    return render(request, 'customers/create_customers.html', context)


def edit_customer(request,pk):
    customer = Customer.objects.get(pk=pk)
    form = CustomerModelForm(instance=customer)
    if request.method == 'POST':
        form = CustomerModelForm(request.POST, request.FILES ,instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customers:customer_details', pk)

    context = {
        'form': form,
        'customer': customer
    }
    return render(request,'customers/edit_custopmers.html', context=context)



def delete_customer(request, pk):
    try:

        customer = get_object_or_404(Customer, id=pk)
        customer.delete()
        return redirect('customers:customer')

    except Customer.DoesNotExist as e:
        print(e)


def load_details(request):
    format = request.GET.get('format','')
    response = None

    if format == 'json':
        response = HttpResponse(content_type='application/json')
        data = list(Customer.objects.all().values('name','email','address','phone','VAT_number','description','password'))
        for customer in data:
            customer['phone'] = str(customer['phone'])
        response.write(json.dumps(data, indent=4))
        response['Content-Disposition'] = 'attachment; filename="customers.json"'


    elif format == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="customers.csv"'
        writer = csv.writer(response)
        writer.writerow(['Id','Name','email','phone','address','description','VAT_number','password'])
        for customer in Customer.objects.all():
            writer.writerow([customer.id,customer.name,customer.email,customer.phone,customer.address,customer.VAT_number,customer.password])

    elif format == 'xlsx':
        customs = Customer.objects.all().values()
        df = pd.DataFrame(list(customs))
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename="customers.xlsx"'
        writer = pd.ExcelWriter(response)
        
    else:
        response = HttpResponse(status=404)
        response.content = 'BAD REQUEST'

    return response






# Aggregate
# from customers.models import Customer
# from django.db.models import Max, Min, Count, Avg
# Customer.objects.all().aggregate(Count('id'))
# Result: {'id__count': 3}


# Customer.objects.all().aggregate(Avg('id'))
# Result: {'id__avg': 6.0}

# Customer.objects.all().aggregate(result = Avg('id'))
# {'result': 6.0}


# Annotate
# from customers.models import Customer
# from django.db.models import Max, Min, Count, Avg

# Customer.objects.all().annotate(name_count=Count('name'))
# Result: <QuerySet [<Customer: Hasan => +998653652547>, <Customer: Oppoq qor => +998775556633>, <Customer: Oppoq => +998991464146>]>


# custom = Customer.objects.all().annotate(name_count=Count('name'))
# >>> for i in custom:
# ...     print(i.email,i.name_count)
# Result: vcsjgvguS@gmail.com 1, qoraqr@gmail.com 1, qoraqor@gmail.com 1

# custom = Customer.objects.all().annotate(name_count=Count('name')).order_by('-name_count')
# Result: <QuerySet [<Customer: Hasan => +998653652547>, <Customer: Oppoq qor => +998775556633>, <Customer: Oppoq => +998991464146>]>



# product = Product.objects.all().annotate(product_count=Count('name')).order_by('-price')
# Result: <QuerySet [<Product: Oppoq qor>, <Product: MacBook Pro>]>



# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------Har Bir categoryda nechta product bor--------------------------------------
# category = Category.objects.all().annotate(category_count=Count('products'))

# for i in category:
# ...     print(i.name, i.category_count)
# Result: Laptops 1, zdbz 1

# ------------------- Har bir categoryda eng qimmat productlar  --------------------------
# category = Category.objects.all().annotate(category_count=Max('products__price'))

# for i in category:
# print(i.name,i.category_count)
# Result: Laptops 777777.77, zdbz 8888888.88


# ------------------------------ Har bir categoryda eng arzon product ------------------------------
# category = Category.objects.all().annotate(category_count=Min('products__price'))

# for i in category:
# print(i.name,i.category_count)
# Result: Laptops 7777.00
# zdbz 8888888.88 Bu categoryda yagona product


# ------------------------------ Har bir categoryda ortacha product ------------------------
# category = Category.objects.all().annotate(category_count=Avg('products__price'))

# for i in category:
# print(i.name,i.category_count)
# Result: Laptops 392777.385000000000, zdbz 8888888.880000000000

shops/views.py
from audioop import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from shops.forms import CommentModelForm, ProductModelForm, AttributeModelForm, AttributeValueModelForm, ProductAttributeForm
from shops.models import Product, ProductImages, Category, ProductAttribute, Comment, Attribute, AttributeValue


# Create your views here.

def app1_view(request):
    url = reverse('customers:customer.html')
    return HttpResponseRedirect(url)

def index(request, slug=None):
    categories = Category.objects.all()
    products = Product.objects.all()
    product_attributes = ProductAttribute.objects.filter()
    search_query = request.GET.get('q','')

    if search_query:
        products = Product.objects.filter(name__icontains=search_query)

    if slug:
        products = Product.objects.filter(category__slug=slug)

    paginator = Paginator(products, 1)
    page_number = request.GET.get('page','1')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'products':products,
        'categories':categories,
    }

    return render(request,  'shops/product-list.html', context=context)


def detail(request, slug=None):
    product = get_object_or_404(Product, category__slug=slug)
    comments = Comment.objects.filter(product=product,is_negative=False)
    context = {
        'product':product,
        'comments':comments,
    }
    return render(request,'shops/product-details.html',context=context)


def comment(request, pk):
    product = get_object_or_404(Product, id=pk)
    form = CommentModelForm()
    if request.method == 'POST':
        form = CommentModelForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = product
            comment.save()
            return redirect('shops:detail', pk)

    context = {
        'product':product,
        'form':form,
    }
    return render(request, 'shops/product-details.html', context=context)


# @login_required
# def create_product(request):
#     form =  ProductModelForm()
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('shops:index')
#     else:
#         form = ProductModelForm()
#
#     context = {
#         'form': form
#     }
#     return render(request, 'shops/create-product.html', context)

# @login_required
# def edit_product(request, pk):
#     product = get_object_or_404(Product, id=pk)
#     form = ProductModelForm(instance=product)
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             return redirect('shops:detail', pk)
#
#     context = {
#         'form':form,
#         'product':product,
#     }
#     return render(request, 'shops/edit-product.html', context=context)


@login_required
def delete_product(request, pk):
    try:
        product = get_object_or_404(Product, id=pk)
        product.delete()
        return redirect('shops:index')
    except Product.DoesNotExist as e:
        print(e)


# @login_required
# def create_attribute(request):
#         form =  AttributeModelForm()
#         if request.method == 'POST':
#             form = AttributeModelForm(request.POST, request.FILES)
#             if form.is_valid():
#                 form.save()
#                 return redirect('shops:create_attribute')
#
#         else:
#             form = AttributeModelForm()
#
#         context = {
#             'form': form
#         }
#
#         return render(request, 'shops/add_atribute.html', context)
#
# @login_required
# def create_attribute_value(request):
#         form =  AttributeValueModelForm()
#         if request.method == 'POST':
#             form = AttributeValueModelForm(request.POST, request.FILES)
#             if form.is_valid():
#                 form.save()
#                 return redirect('shops:create_attribute_value')
#
#         else:
#             form = AttributeValueModelForm()
#
#         context = {
#             'form': form
#         }
#         return render(request, 'shops/add_attribute_value.html', context)
#
#
# @login_required
# def product_attribute_value(request):
#         form =  ProductAttributeForm()
#         if request.method == 'POST':
#             form = ProductAttributeForm(request.POST, request.FILES)
#             if form.is_valid():
#                 form.save()
#                 return redirect('shops:product-attribute')
#
#         else:
#             form = ProductAttributeForm()
#
#         context = {
#             'form': form,
#         }
#
#         return render(request, 'shops/product-attribute.html', context)
#


class CreateProduct(CreateView):
    model = Product
    template_name = 'shops/create-product.html'
    form_class = ProductModelForm
    success_url = reverse_lazy("shops:index")

class EditProduct(UpdateView):
    model = Product
    template_name = 'shops/edit-product.html'
    form_class = ProductModelForm
    success_url = reverse_lazy("shops:index")

class CreateAttribute(CreateView):
    model = Attribute
    template_name = 'shops/add_atribute.html'
    form_class = AttributeModelForm
    success_url = reverse_lazy("shops:create_attribute")

class AttributeValeu(CreateView):
    model = Attribute
    template_name = 'shops/add_attribute_value.html'
    form_class = AttributeValueModelForm
    success_url = reverse_lazy("shops:create_attribute_value")

class CreateProductAttribute(CreateView):
    model = ProductAttribute
    template_name = 'shops/product-attribute.html'
    form_class = ProductAttributeForm
    success_url = reverse_lazy("shops:product-attribute")

shops/templates/shops/add_atribute.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Create</title>
      <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <!-- Navbar -->
    <header class="bg-blue-600 text-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-4 px-6">
            <h1 class="text-2xl font-bold">Attribute Create</h1>
            <nav>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Attribute</a>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Contact</a>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto my-10">
        <div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Add New Attribute</h2>
            <!-- Form -->
           <form action="{% url 'shops:create_attribute' %}" method="POST" class="space-y-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                
                {% if user.is_authenticated %}
                    <button type="submit"
                            class="w-full bg-blue-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-blue-700 transition">
                            Create Attribute
                    </button>
                {% endif %}
                
                <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:index' %}"> Cancel </a>
                </div>
            <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:create_attribute_value' %}"> Next </a>
                </div>
            </form>

        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto text-center">
            <p>&copy; By Aslan 2025</p>
        </div>
    </footer>
</body>
</html>

shops/templates/shops/add_attribute_value.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Create</title>
      <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <!-- Navbar -->
    <header class="bg-blue-600 text-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-4 px-6">
            <h1 class="text-2xl font-bold">Attribute Value Create</h1>
            <nav>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Attribute Value</a>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Contact</a>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto my-10">
        <div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Add New Attribute Value</h2>
            <!-- Form -->
           <form action="{% url 'shops:create_attribute_value' %}" method="POST" class="space-y-4" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                
                {% if user.is_authenticated %}
                    <button type="submit"
                            class="w-full bg-blue-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-blue-700 transition">
                            Create Attribute Value
                    </button>
                {% endif %}
                
                <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:index' %}"> Cancel </a>
                </div>
            <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:product-attribute' %}"> Next </a>
                </div>
            </form>

        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto text-center">
            <p>&copy; By Aslan 2025</p>
        </div>
    </footer>
</body>
</html>

shops/templates/shops/create-product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Create</title>
      <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <!-- Navbar -->
    <header class="bg-blue-600 text-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-4 px-6">
            <h1 class="text-2xl font-bold">Product Create</h1>
            <nav>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Products</a>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Contact</a>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto my-10">
        <div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Add New Product</h2>
            <!-- Form -->
            <form action="{% url 'shops:create_product' %}" method="POST" class="space-y-4" enctype="multipart/form-data">
              {{ form.as_p }}<br>
                {% if user.is_authenticated %}
                  <button type="submit"
                          class="w-full bg-blue-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-blue-700 transition">
                          Create Product
                  </button>

                {% endif %}
                {% csrf_token %}
                <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:index' %}"> Cancel </a>
                </div>
            </form>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto text-center">
            <p>&copy; By Aslan 2025</p>
        </div>
    </footer>
</body>
</html>

shops/templates/shops/edit-product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Product</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">

    <!-- Navbar -->
    <header class="bg-blue-600 text-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-4 px-6">
            <h1 class="text-2xl font-bold">
                <a href="{% url 'shops:detail' product.id %}" class="text-white hover:text-gray-200 ml-4"> OLD {{ product.name }}</a>
            </h1>
            <nav>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Contact</a>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto my-10">
        <div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Edit Product</h2>
            <!-- Form -->
            <form id="editForm" action="#" method="POST" class="space-y-4" enctype="multipart/form-data">
                {{ form.as_p }}
                <button type="button" class="w-full bg-blue-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-blue-700 transition" onclick="showConfirmation()">Edit Product</button>
                {% csrf_token %}
                <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:index' %}"> Cancel </a>
                </div>
            </form>

            <!-- Modal for Edit Confirmation -->
            <div id="confirmationModal" style="display:none;">
                <div class="modal-content">
                    <h2>Are you sure you want to Edit?</h2>
                    <button class="yes-btn" onclick="confirmEdit()">Yes</button>
                    <button class="no-btn" onclick="closeModal()">No</button>
                </div>
            </div>

            <script type="text/javascript">
                function showConfirmation() {
                    document.getElementById("confirmationModal").style.display = "flex";
                }

                function confirmEdit() {
                    // Check if any field has been changed
                    let formModified = false;
                    const formElements = document.querySelectorAll('#editForm input, #editForm textarea, #editForm select');
                    formElements.forEach(element => {
                        if (element.value !== element.defaultValue) {
                            formModified = true;
                        }
                    });

                    if (formModified) {
                        // If changes are made, submit the form
                        document.getElementById("editForm").submit();
                    } else {
                        alert('No changes were made.');
                        closeModal();
                    }
                }

                function closeModal() {
                    document.getElementById("confirmationModal").style.display = "none";
                }
            </script>

            <style>
                #confirmationModal {
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    background-color: rgba(0, 0, 0, 0.5);
                    display: none;
                    justify-content: center;
                    align-items: center;
                }

                .modal-content {
                    background-color: white;
                    padding: 15px;
                    border-radius: 10px;
                    text-align: center;
                    width: 300px;
                    min-width: 250px;
                }

                .modal-content h2 {
                    margin-bottom: 15px;
                    font-size: 18px;
                }

                .yes-btn {
                    background-color: green;
                    color: white;
                    border: none;
                    padding: 8px 16px;
                    margin: 5px;
                    cursor: pointer;
                    border-radius: 5px;
                }

                .no-btn {
                    background-color: red;
                    color: white;
                    border: none;
                    padding: 8px 16px;
                    margin: 5px;
                    cursor: pointer;
                    border-radius: 5px;
                }

                .yes-btn:hover {
                    background-color: darkgreen;
                }

                .no-btn:hover {
                    background-color: darkred;
                }
            </style>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto text-center">
            <p>&copy; By Aslan 2025</p>
        </div>
    </footer>
</body>
</html>

shops/templates/shops/product-attribute.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Attribute Create</title>
      <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50">
    <!-- Navbar -->
    <header class="bg-blue-600 text-white shadow-lg">
        <div class="container mx-auto flex justify-between items-center py-4 px-6">
            <h1 class="text-2xl font-bold">Product Attribute Create</h1>
            <nav>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Product Attribute</a>
                <a href="#" class="text-white hover:text-gray-200 ml-4">Contact</a>
            </nav>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container mx-auto my-10">
        <div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Add New Product Attribute</h2>
            <!-- Form -->
            <form action="{% url 'shops:product-attribute'  %}" method="POST" class="space-y-4" enctype="multipart/form-data">
              {{ form.as_p }}<br>
                {% if user.is_authenticated %}
                  <button type="submit"
                          class="w-full bg-blue-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-blue-700 transition">
                          Create Product Attribute
                  </button>
                {% endif %}
                {% csrf_token %}
                <div class="col-1">
                    <a class="btn btn-outline-warning" href="{% url 'shops:index' %}"> Cancel </a>
                </div>

            </form>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-800 text-white py-4">
        <div class="container mx-auto text-center">
            <p>&copy; By Aslan 2025</p>
        </div>
    </footer>
</body>
</html>